### ISSUE TITLE
Overriding of variables works for .class-names but when using variables they have default values

### ISSUE THREAD

**Issue by yup-ma** [yup-ma/yupma-ui-styles#1]
Global.scss:
```css
  $blue: red;
  @import '@yupma/ui-styles/lib/scss/yupma_ui.scss';
``` 
This worked for classes: now `.ym-bg-blue-100` have a reddish tint same goes for classes using `$blue`. Expected behavior.

But when used the variable:
```css
@use '@yupma/ui-styles/lib/scss/variables.scss' as *;
.custom-class {
  text-decoration: underline;
  background-color: $blue !important;
}
``` 
Expected as it is importing original from library but when used `@use 'path-to/gloabl.scss' as *;` not custom css is applied not even text decoration underline. So variables are inaccessible...
